In [1]:
import pandas as pd
import numpy as np
import os
import random

# 设置显示选项
pd.set_option('display.max_colwidth', 100)

In [4]:
def data_basic_information(df):

    pd.set_option('display.max_columns', None)
    pd.set_option('display.max_rows', None)

    print(f"数据行数: {df.shape[0]}")
    print(f"数据列数: {df.shape[1]}") 

    dtypes = df.dtypes.value_counts()
    print("\n数据类型分布:")
    for dtype, count in dtypes.items():
        print(f"- {dtype}: {count}列")

    print("\n列信息:")
    column_info = pd.DataFrame({
        '数据类型': df.dtypes,
        '非空值数量': df.count(),
        '空值数量': df.isnull().sum(),
        '空值百分比': (df.isnull().sum() / len(df) * 100).round(2),
        '唯一值数量': df.nunique(),
        '唯一值': {column: df[column].unique() for column in df.columns}
    })
    display(column_info)

    print("\n数值列的统计描述:")
    display(df.describe().T)

    cat_columns = df.select_dtypes(include=['object', 'category']).columns
    if not cat_columns.empty:
        print("\n分类列的统计描述:")
        cat_stats = pd.DataFrame({
            '唯一值数量': df[cat_columns].nunique(),
            '最常见值': [df[col].value_counts().index[0] if not df[col].value_counts().empty else None for col in cat_columns],
            '最常见值频次': [df[col].value_counts().iloc[0] if not df[col].value_counts().empty else 0 for col in cat_columns],
            '最常见值占比': [(df[col].value_counts().iloc[0] / df[col].count() * 100).round(2) if not df[col].value_counts().empty else 0 for col in cat_columns]
        })
        cat_stats['最常见值占比'] = cat_stats['最常见值占比'].astype(str) + '%'
        display(cat_stats)

In [3]:
file_path = 'Youtube01.csv'
data = pd.read_csv(file_path)
data.shape

(1956, 5)

In [6]:
data['CLASS'] = data['CLASS'].astype(object)

In [7]:
data_basic_information(data)

数据行数: 1956
数据列数: 5

数据类型分布:
- object: 5列

列信息:

,数据类型,非空值数量,空值数量,空值百分比,唯一值数量,唯一值
COMMENT_ID,object,1956,0,0.00,1953,"[LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU, LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A, LZQPQ..."
AUTHOR,object,1956,0,0.00,1792,"[Julius NM, adam riyati, Evgeny Murashkin, ElNino Melendez, GsMega, Jason Haddad, ferleck ferles..."
DATE,object,1711,245,12.53,1709,"[2013-11-07T06:20:48, 2013-11-07T12:37:15, 2013-11-08T17:34:21, 2013-11-09T08:28:43, 2013-11-10T..."
CONTENT,object,1956,0,0.00,1760,"[Huh, anyway check out this you[tube] channel: kobyoshi02, Hey guys check out my new channel and..."
CLASS,object,1956,0,0.00,2,"[1, 0]"

数值列的统计描述:

           count unique                                          top  freq
COMMENT_ID  1956   1953  _2viQ_Qnc68fX3dYsfYuM-m4ELMJvxOQBmBOFHqGOk0     2
AUTHOR      1956   1792                                        M.E.S     8
DATE        1711   1709                   2013-10-05T00:57:25.078000     2
CONTENT     1956   1760            Check out this video on YouTube:﻿    97
CLASS       1956      2                                            1  1005

分类列的统计描述:

            唯一值数量                                         最常见值  最常见值频次  最常见值占比
COMMENT_ID   1953  _2viQ_Qnc68fX3dYsfYuM-m4ELMJvxOQBmBOFHqGOk0       2    0.1%
AUTHOR       1792                                        M.E.S       8   0.41%
DATE         1709                   2013-10-05T00:57:25.078000       2   0.12%
CONTENT      1760            Check out this video on YouTube:﻿      97   4.96%
CLASS           2                                            1    1005  51.38%

In [2]:
file_path = 'comments_analysis_v1.csv'
df = pd.read_csv(file_path)
df.shape

(51730, 8)

In [11]:
def random_comment_samples(df):
    spam_comments = df[df['Prediction'] == 'SPAM COMMENT']
    non_spam_comments = df[df['Prediction'] == 'NOT A SPAM COMMENT']

    print(f"\n找到 {len(spam_comments)} 条垃圾评论")
    print(f"找到 {len(non_spam_comments)} 条非垃圾评论")

    random_spam = spam_comments.sample(min(10, len(spam_comments)))
    random_non_spam = non_spam_comments.sample(min(10, len(non_spam_comments)))

    print("\n\n=== 10 random spam comments ===\n")
    for i, (_, row) in enumerate(random_spam.iterrows(), 1):
        print(f"Spam Comments #{i}:")
        print(f"Content Creator: {row.get('Content Creator', 'N/A')}")
        if 'Video Title' in row:
            print(f"Video Title: {row['Video Title']}")
        print(f"Comment: {row['Comment']}")
        print("-" * 80)

    print("\n\n=== Random 10 non-spam comments ===\n")
    for i, (_, row) in enumerate(random_non_spam.iterrows(), 1):
        print(f"Non-spam Comments #{i}:")
        print(f"Content Creator: {row.get('Content Creator', 'N/A')}")
        if 'Video Title' in row:
            print(f"Video Title: {row['Video Title']}")
        print(f"Comment: {row['Comment']}")
        print("-" * 80)

    random_samples = pd.concat([random_spam, random_non_spam])
    return random_samples

In [12]:
random_samples = random_comment_samples(df)

# 保存随机样本到CSV文件
# output_file = 'random_comment_samples.csv'
# random_samples.to_csv(output_file, index=False)
# print(f"\n随机评论样本已保存到: {output_file}")

找到 12705 条垃圾评论
找到 39018 条非垃圾评论


=== 10 random spam comments ===

Spam Comments #1:
Content Creator: Now You Know
Video Title: nan
Comment: For a small issue.. a Tesla rover arrived and fixed my potential recall issue in 20 mins.  For repairs to my car after it was backed into.. it took over a month for parts
--------------------------------------------------------------------------------
Spam Comments #2:
Content Creator: Electric Vehicle Man
Video Title: nan
Comment: Hi, sorry to bother you again (next time it’ll be the salesman!) One final question, you say you plug the car in at home to stay charged up. Just wondering if the Leaf has a means of stopping you driving off while still plugged in? I know it’s a little extreme but having owned a conventional car for xx years I’m used to just jumping in and driving off. I’m only too aware of what can happen in a momentary distraction and we’ve all heard of people leaving the garage forecourt and leaving their fuel cap behind or the flap open, lights on overnight etc. Thanks for your patience, take care. Peter
--------------------------------------------------------------------------------
Spam Comments #3:
Content Creator: Fully Charged Show
Video Title: nan
Comment: 62mph is not safe at motorway speeds it may be road legal but it would be like riding a learner legal ICE motorbike when can we see some real motorbikes which will be safe at motorway speeds which are capable of matching the performance of even a motorcycle from the 70's? Personally I'm not a fan of dirt bikes give me a sports bike or 70's style cafe racer, or maybe even a sports tourer, and make that electric and then we can talk, but dirt bikes are toys nothing more.
--------------------------------------------------------------------------------
Spam Comments #4:
Content Creator: Fully Charged Show
Video Title: nan
Comment: The Vin Group is similar to BYD in how vertically integrated they are.

On to the car. It's OK looking. It looks Hyundai and Porsche had a child together. The tail lights are similar in that look and feel of the Mach E. The interior is nice and looks very spacious. No moon roof could possibly make it feel dark but it's not a deal breaker for some. What they have done nicer than VW is put a proper infotainment screen in this SUV and not that clunky looking monochromatic thing VW is trotting out there to consumers

Other than not having much in the way of specs to share with us right now I will say that the WLTP range of 293 miles seems very, very poor. If we translate that to US EPA range that might be 250 miles or less. That seems like it just won't cut it for such a large vehicle that would be geared for road trips given it's size. It's nice to see what they've put forth so far. I'm hoping they have better..especially if they want to go after the US market.
--------------------------------------------------------------------------------
Spam Comments #5:
Content Creator: Now You Know
Video Title: nan
Comment: The GRID is next to get stranded.
Our forebears built the grid to distribute power from centralised plants to all around. That is starting to roll back, with Australia and rural communities around the globe as examples.
As energy is generated locally by solar plants, only 'filler' energy is needed. That lesser 'filler' energy is now transmitted from a far-off plant by long wires.
Meanwhile, PV and batteries will become even cheaper. So you will also generate the 'filler' energy on your roof, which means that you've become self-contained.
Thus the grid transmits fewer energy units (kWh). But the grid cost remains the same. So each energy unit needs to carry a higher price (to replace the grid).
Today the cost of replacement is disguised by the grid already being here.
But as the grid ages, we need to maintain and replace sections. At that moment, we calculate if there's still enough energy carried on the line to justify the cost of replacement.
And so, already today, some transmission cables are not replaced.
We're at the start of that particular S-curve, but it will soon accelerate. In 10 years, the grid will be unimportant, and in 15 years, it will be gone. And with that, all the power plants (nuclear, coal, gas, wind, solar, hydro) along the line will be stranded.
Mobile phones became accepted within a small group about 25 years ago. How many telephone lines do you still see today? The same will be true of solar panels on roofs and High Voltage transmission lines.
However, one does need to be aware of latitude (how close to the North and South Pole). Closer to the Poles, solar PV is not as effective as it is close to the equator. So wind still makes a lot of sense close to the (Ant-)Arctic. And there, transmission wires continue to make sense.
But as solar becomes cheaper, wind power will lose importance. And thus the demise of transmission lines.
--------------------------------------------------------------------------------
Spam Comments #6:
Content Creator: Now You Know
Video Title: nan
Comment: Sounds pretty spot on from my perspective. I just test drove a model 3 last weekend and it was such a smooth ride. I have no intention of getting a non-ev ever again.

My VW Passat can't hold a candle to the model 3. Still I'll be waiting until it fits my budget. Specifically I'm waiting until I'm no longer upside-down on my current car before I trade up. The standard battery should be available by then and it should be a simple transition from there with a similar monthly payment.
--------------------------------------------------------------------------------
Spam Comments #7:
Content Creator: Fully Charged Show
Video Title: nan
Comment: I don't like the idea of "steer by wire".  No power, no steering.  Same goes for electrically controlled brakes.

I've had my "throttle by wire" crap out on me while trying to get onto an interstate.  Accelerating up the ramp and suddenly no power.  Not a good experience.
--------------------------------------------------------------------------------
Spam Comments #8:
Content Creator: Now You Know
Video Title: nan
Comment: I absolutely love these videos - especially when you have "those" debates with EV skeptics; good to refer to. Only thing I could ask for more (and it's just to really hammer the arguments home), would be to link sources - like average kWh prices. I know it's easily Googable (should be a word!), but if shown on screen it would just make the video seems even MORE credible than it already is :) I know it would require more work behind the scenes, and again I personally don't need it, I can do that myself - it's more meant as a suggestion to make the videos as a whole go from 10 to 11 :D

LOVE your work guys and gals!
--------------------------------------------------------------------------------
Spam Comments #9:
Content Creator: Now You Know
Video Title: nan
Comment: This kid is on to something. Its perfect because the die hard gas equipment companies will never pivot. By the time they catch on, this kids company will be dominating the territory. Pitch the noise reduction aspect hard. That's a big advantage in my opinion. Also, if your expenses are that low, you can undercut (no pun intended) the competition. Good job man.
--------------------------------------------------------------------------------
Spam Comments #10:
Content Creator: Fully Charged Show
Video Title: nan
Comment: Ricky looks like a tall guy, his eye line was inline with dash. Plus the orange background made it look like cgi. in fact I suspect some of the road driving shots were cgi

Looks amazing. love the colour. but for real it's just a look at me mock up. nice but no dice. 👍
--------------------------------------------------------------------------------


=== Random 10 non-spam comments ===

Non-spam Comments #1:
Content Creator: E for Electric
Video Title: nan
Comment: Thanks again Alex, for great information.
--------------------------------------------------------------------------------
Non-spam Comments #2:
Content Creator: Now You Know
Video Title: nan
Comment: 11:04. Poor elected official conduct. You must resurrect the idea of official conduct. And stop caring who people vote for, and start recognizing integrity.
--------------------------------------------------------------------------------
Non-spam Comments #3:
Content Creator: Fully Charged Show
Video Title: nan
Comment: No, i wouldn't.
--------------------------------------------------------------------------------
Non-spam Comments #4:
Content Creator: Fully Charged Show
Video Title: nan
Comment: This was really fun. U 2 R soooooooooooo cute. 🙂 I expect E-Scooters to become popular in a few years for longer trips and to use on roads. but for areas that are safe and exclusive for "bicycles" the  E-bikes will be popular, esp as costs come down.
--------------------------------------------------------------------------------
Non-spam Comments #5:
Content Creator: Fully Charged Show
Video Title: nan
Comment: 60 countries ..?  LOL.. this car will get their ass kick by BYD seagull, Binguo or any chinese small car with almost half the price in any country  outside europe and usa.
--------------------------------------------------------------------------------
Non-spam Comments #6:
Content Creator: Fully Charged Show
Video Title: nan
Comment: The interior is really nice and modern with the contrasting colours but the exterior lacks in character - it's no Honda E or Hyundai Inster.
--------------------------------------------------------------------------------
Non-spam Comments #7:
Content Creator: Fully Charged Show
Video Title: nan
Comment: I genuinely love this car
--------------------------------------------------------------------------------
Non-spam Comments #8:
Content Creator: Electric Vehicle Man
Video Title: nan
Comment: Have you ever measured how many KwH your meter clocks as you fully charge a 50kw Tesla model 3 battery? I think you are severely underestimating the efficiency. I think the efficiency is less than 70% with the cooling fan power use and heat wasted into the air while charging.
--------------------------------------------------------------------------------
Non-spam Comments #9:
Content Creator: Fully Charged Show
Video Title: nan
Comment: ~£1K for THAT?? And you have to assemble it? And range - and power - is shite? Roll eyes.
--------------------------------------------------------------------------------
Non-spam Comments #10:
Content Creator: Fully Charged Show
Video Title: nan
Comment: Looks okay outside, but man the interior is like 10-15 years to old
--------------------------------------------------------------------------------

In [13]:
file_path = 'comments_analysis_v2.csv'
df = pd.read_csv(file_path)
df.shape

(51730, 8)

In [14]:
random_samples = random_comment_samples(df)

找到 33061 条垃圾评论
找到 18662 条非垃圾评论


=== 10 random spam comments ===

Spam Comments #1:
Content Creator: Bjorn Nyland
Video Title: nan
Comment: Bjørn. Try to slipstream behind flybussen FB12 to sarpsborg. They keep a steady speed of 103kmh gps. Some of the rutetider don’t have many stops
--------------------------------------------------------------------------------
Spam Comments #2:
Content Creator: E for Electric
Video Title: nan
Comment: I mean, the H2 situation is half as efficient using the energy. So more weight, better energy efficiency. Not sure how I would feel about an airplane with H2 in it... But also I don't see airplanes getting off fossil fuels any time soon without a lot of reduction in flying.
--------------------------------------------------------------------------------
Spam Comments #3:
Content Creator: Now You Know
Video Title: nan
Comment: Nice find Zac! Cool that Mitch is Canadian...way to go, eh? I can relate to Mitch as I used to sell an electric multi-purpose tractor  here in Nova Scotia called the Electric Ox...electric rocks! About the truck you are wishing for Mitch, have you heard about the Havelaar Bison? Here's a link for it: http://www.havelaarcanada.com/bison/ Very inspiring Mitch, keep up the great work! Zac, keep showcasing these types of guys and businesses...very interesting!!! Cheers, John ;)
--------------------------------------------------------------------------------
Spam Comments #4:
Content Creator: Now You Know
Video Title: nan
Comment: check out Mean Green. they sell zero turn battery mowers and other battery commercial equipment
--------------------------------------------------------------------------------
Spam Comments #5:
Content Creator: Electric Vehicle Man
Video Title: nan
Comment: Are there any plug in hybrids which are good at long journeys (over 200 miles)? I realise that most are not, but would be very interested if any were.
--------------------------------------------------------------------------------
Spam Comments #6:
Content Creator: Now You Know
Video Title: nan
Comment: Get ready for universal basic income.
--------------------------------------------------------------------------------
Spam Comments #7:
Content Creator: Fully Charged Show
Video Title: nan
Comment: You don't drive a motorcycle you ride it! So infuriating.. 😂😂
--------------------------------------------------------------------------------
Spam Comments #8:
Content Creator: Fully Charged Show
Video Title: nan
Comment: Reminds me of my father's car when I was a 10-ish y.o. boy.
--------------------------------------------------------------------------------
Spam Comments #9:
Content Creator: Fully Charged Show
Video Title: nan
Comment: I want one if it’s that price where I live. But unfortunately it’s 3 times the price.
--------------------------------------------------------------------------------
Spam Comments #10:
Content Creator: E for Electric
Video Title: nan
Comment: Alex, I don’t believe GM will have access to all of Tesla’s chargers. And as much as I too love the new Silverado EV, I did not put down a deposit because I don’t want to pay the stealership mark ups!
--------------------------------------------------------------------------------


=== Random 10 non-spam comments ===

Non-spam Comments #1:
Content Creator: Fully Charged Show
Video Title: nan
Comment: EV4 Looks great - like it a lot
--------------------------------------------------------------------------------
Non-spam Comments #2:
Content Creator: Fully Charged Show
Video Title: nan
Comment: Looks like the future. Looking forward to it.
--------------------------------------------------------------------------------
Non-spam Comments #3:
Content Creator: Now You Know
Video Title: nan
Comment: Absolutely right, don't forget hydro power. Also I hope you are going to upgrade that house insulation whilst you are doing the heating. 😉
--------------------------------------------------------------------------------
Non-spam Comments #4:
Content Creator: Fully Charged Show
Video Title: nan
Comment: Love the design but can see a lot of potential issues in the long term. Will it ever come to the EU? Hopefully so & also hope the price despondent skyrocket!
--------------------------------------------------------------------------------
Non-spam Comments #5:
Content Creator: Fully Charged Show
Video Title: nan
Comment: What a waiste of space. The driver's compartment takes 50% of the vehicle space
--------------------------------------------------------------------------------
Non-spam Comments #6:
Content Creator: Bjorn Nyland
Video Title: nan
Comment: Pool jump challenge 😜
--------------------------------------------------------------------------------
Non-spam Comments #7:
Content Creator: Fully Charged Show
Video Title: nan
Comment: It's a grand to put onto your existing bike a pedal assist. Why?
--------------------------------------------------------------------------------
Non-spam Comments #8:
Content Creator: Now You Know
Video Title: nan
Comment: I saw my first rivian in the wild this past weekend. It was dead in the middle of the freeway, causing a major backup. My Tesla drove me around it though
--------------------------------------------------------------------------------
Non-spam Comments #9:
Content Creator: Fully Charged Show
Video Title: nan
Comment: I cannot see the point
--------------------------------------------------------------------------------
Non-spam Comments #10:
Content Creator: Now You Know
Video Title: nan
Comment: Bernice is a psycho. I support Green movement but socialist wroth nothing but death and destruction
--------------------------------------------------------------------------------

In [15]:
file_path = 'comments_analysis_v3.csv'
df = pd.read_csv(file_path)
df.shape
random_samples = random_comment_samples(df)

找到 6368 条垃圾评论
找到 45355 条非垃圾评论


=== 10 random spam comments ===

Spam Comments #1:
Content Creator: Now You Know
Video Title: nan
Comment: I've seen her channel before and it's a bit of a joke. Thanks for taking these stupid arguments on!
--------------------------------------------------------------------------------
Spam Comments #2:
Content Creator: E for Electric
Video Title: nan
Comment: Unbiased reporting is why I’m subbed.   I dont get the Musky ass lickers.  I own and 2021 and a 2023 Y.   Removing USS bugs me every MF day, esp knowing how great it was with it.  I gave my 2021 to my mother…just recently…the AC would switch to max heat 🤦🏻‍♂️.  Poor mama was driving in summer FL with a 100+ cabin.   Quick soft reset did the job, but I can NOT wait until Tesla has stiff competition.  Elon got too big for his britches.
--------------------------------------------------------------------------------
Spam Comments #3:
Content Creator: Bjorn Nyland
Video Title: nan
Comment: I like how these new circumstances in life make Bjorn to give us more and more practical tests. I hope the stroller test will become part of the standard testing procedure from now on 🙂
--------------------------------------------------------------------------------
Spam Comments #4:
Content Creator: Now You Know
Video Title: nan
Comment: Tunnels too narrow for my comfort
--------------------------------------------------------------------------------
Spam Comments #5:
Content Creator: Fully Charged Show
Video Title: nan
Comment: Who won the electric car? I have suscribed since long back and not got any.. Fake channel!
--------------------------------------------------------------------------------
Spam Comments #6:
Content Creator: Electric Vehicle Man
Video Title: nan
Comment: Completely off topic - but this certainly isn't efficient https://www.theguardian.com/money/2020/nov/28/electric-cars-porsche-charging-network
--------------------------------------------------------------------------------
Spam Comments #7:
Content Creator: Now You Know
Video Title: nan
Comment: I really love Aptera and their aerodynamic design. I hope their success but I think their focus on solar is misdirected and might lead to their bankruptcy. It's such a small benefit and return on investment. They should focus on getting their cars in production first without them and add that feature later. Even as a consumer I'd rather save the cost invested in solar R and D and put it on my house roof to be actually sustainable
--------------------------------------------------------------------------------
Spam Comments #8:
Content Creator: Now You Know
Video Title: nan
Comment: Guys I feel sorry for you having to read this out publicly. I did my duty and read and listened to the whole email as you read it out. It was physically painful to experience. How you managed to get through it without suffering permanent mental health issues I don't know. Maybe you didn't. I feel you guys deserve a holiday just to get over reading out that 24-karat bull crap. Well done. You took one for the team. I could never have read or listened to that whole thing if you weren't there with me to see me through it. I feel dirty. I need to shower. But, I'll get over it. Eventually.
--------------------------------------------------------------------------------
Spam Comments #9:
Content Creator: Now You Know
Video Title: nan
Comment: I think even if it’s going to take longer for Optimus to realise its full potential, Tesla can offer a package to all industries looking to scale up their processes incorporating more automation, computing power and greater quality capabilities based on what they learned, and continue to learn. It’s a huge potential for Tesla automation and robotics business! Then, when Optimus really gets going there is simply no limits for the value of the company stock! Even small investors like me can win big as time goes by!
--------------------------------------------------------------------------------
Spam Comments #10:
Content Creator: Electric Vehicle Man
Video Title: nan
Comment: In Australia where long journeys are more common they ask drivers to stop every two hours its called "Drive,Revive, Survive" . Up until the mid 1990's I recall many ICE cars had range anxiety as most couldn't go past 500 klms or 300 miles and in the 1970s/80s not many petrol stations were open after dark in country areas. When I was a young man I had a Honda Civic with about a 500 klm range if I was careful I would drive 5 hours straight before stopping especially on trips between Sydney and Melbourne just over 1,000 klms (600 miles). The longest trip I did just stopping for Petrol and food etc was 1,700 klms in one journey the highlight was on a bend where it looked like I was approaching a Semi (Lorry) but at the last minute another Semi Lorry was trying to overtake it and I literally drove between them in my 1975 Honda Civic...there was no shoulder to this part of the road only two lanes and raised up off ground level as it was going across a flood plain. But there was just enough width for the three of us. I had also just picked up a Hitchhiker who freaked out and asked to be dropped off at the next town. I have been following EVM for a few years as he struck me as a very commonsense person. We can import used Nissan Leaf's usually from Japan but I'd prefer ones from the UK as they have the 6.6 kw charge option (Japanese none have it ) and everything is already in English. But they are usually higher priced. Shipping is almost the same cost.
--------------------------------------------------------------------------------


=== Random 10 non-spam comments ===

Non-spam Comments #1:
Content Creator: Now You Know
Video Title: nan
Comment: This is propaganda. The Russians have legitimate reasons for their actions.  NATO started this Ukraine crisis, and everyone knows it. The US has no business in Europe any more.
--------------------------------------------------------------------------------
Non-spam Comments #2:
Content Creator: E for Electric
Video Title: nan
Comment: Just 3 million watch is little number for this beautiful song i think every one comments here or Listened to this song agree that it’s one of the most wonderful songs they have ever heard . It makes you lives the tragedy of vincent and imagine how he suffered just through the words moreover liana sound and singing make this song as it’s now i listened to it with other singers it looks like any average song i hear thanks liana for this astonishing sound
--------------------------------------------------------------------------------
Non-spam Comments #3:
Content Creator: Now You Know
Video Title: nan
Comment: Total clowns
--------------------------------------------------------------------------------
Non-spam Comments #4:
Content Creator: Now You Know
Video Title: nan
Comment: Those jusges are getting kick backs… someone should look into that… follow the money…. FBI … hello anyone home?
--------------------------------------------------------------------------------
Non-spam Comments #5:
Content Creator: Fully Charged Show
Video Title: nan
Comment: What about repairability?  I've heard that they are assembled almost entirely with adhesive and rivets, so simple body work repairs are way more expensive than legacy autos.  I've also seen articles saying that because of this, insurance on them is high, and often they get totalled for what would be a minor accident in another vehicle.  Can you speak to those concerns?  Also, don't get me wrong, I'm all in on EVs.  I'm also all in on Right to Repair though too, and I would argue that Tesla rates poorly on that.
--------------------------------------------------------------------------------
Non-spam Comments #6:
Content Creator: Now You Know
Video Title: nan
Comment: Can you plug a non-Tesla into a Super charger?  I don't think so......but I think if all the manufactures agreed to a universal plug that would fit on that charger, non-Tesla EV sales would Skyrocket.  Everyone could use that power network.
--------------------------------------------------------------------------------
Non-spam Comments #7:
Content Creator: Now You Know
Video Title: nan
Comment: Twitter without bots, with a sensible user interface with less copycat and more leader of the pack. Sounds like a pretty good thing.
--------------------------------------------------------------------------------
Non-spam Comments #8:
Content Creator: Fully Charged Show
Video Title: nan
Comment: It looks about as happy as a cow at an abbatoir. Is it made by Lego, btw?
--------------------------------------------------------------------------------
Non-spam Comments #9:
Content Creator: Now You Know
Video Title: nan
Comment: If you have automatic steering of e-vehicles through a narrow tunnel, passengers will have to leave a stalled vehicle through a roof hatch, that will be difficult for elderly people or wheelchair users. Adding a sidewalk just wide enough for a wheelchair (like modern subway tunnels have) will make the tunnel more expensive but not that much more expensive when using an advanced tunnel boring system. Note: You need two tunnel bores if you build single-lane tunnels as modern high-speed railway tunnels have (see the Gotthard Base Tunnel, Switzerland).
--------------------------------------------------------------------------------
Non-spam Comments #10:
Content Creator: Bjorn Nyland
Video Title: nan
Comment: e-UP :D
--------------------------------------------------------------------------------